import Head from 'next/head'
import { Grid } from '@components/UI'
import { About, ArtistCard } from '@components/common'
import { PlaylistCard } from '@components/Playlist/PlaylistCard'
import { useEffect, useState } from 'react'
import axios from 'axios';

export async function getStaticProps() {
  // const { data } = await client.query({
  //   query: getAllPlaylistsQuery,
  // })


  return {
    props: {
      data: {
        playlists: [
          {
            id: '1',
            title: 'Playlist 1',
            imageUrl: "https://picsum.photos/200/300"
          }
        ],
        Artists: [
          {
            id: '1',
            name: 'Artist 1',
            imageUrl: "https://picsum.photos/200/300"
          },
          {
            id: '2',
            name: 'Artist 2',
            imageUrl: "https://picsum.photos/200/300"
          }
        ]
      },
    }, // will be passed to the page component as props
  }
}

const GenerateMusic = () => {
  const [text, setText] = useState('');

  return (<>
    <div>
      <div className="flex items-center px-3 py-2 rounded-lg bg-gray-700" color="currentColor">
        <textarea
          onChange={(e) => {
            setText(e.target.value);
          }}
          id="chat" rows={3} className="block mx-4 p-2.5 w-full text-sm text-gray-900 bg-white rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Your message..."></textarea>
        <button onClick={async () => {
          const res = await axios.post('http://127.0.0.1:5000/', {
            lyrics: text.split('\n') || []
          })
          console.log({ res });

          if (res.data.status === 200) {
            setText('');
          }

        }} className="inline-flex justify-center p-2 text-blue-600 rounded-full cursor-pointer hover:bg-blue-100 dark:text-blue-500 dark:hover:bg-gray-600">
          <svg className="w-5 h-5 rotate-90" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
            <path d="m17.914 18.594-8-18a1 1 0 0 0-1.828 0l-8 18a1 1 0 0 0 1.157 1.376L8 18.281V9a1 1 0 0 1 2 0v9.281l6.758 1.689a1 1 0 0 0 1.156-1.376Z" />
          </svg>
          <span className="sr-only">Send message</span>
        </button>
      </div>
    </div >
  </>)
}

const Home = (props: { data: any; error: any }) => {
  const { data, ...rest } = props;
  const [request, setRequest] = useState(data.playlists);

  useEffect(() => {
    (async () => {
      const res = await axios.get('http://127.0.0.1:5000/get-list');
      const currPlaylists = request;

      if (res.status == 200) {
        const result = res.data.result.data.map((item: any, idx: number) => {
          return {
            id: item.key,
            title: `Request ${idx + 2}`,
            imageUrl: "https://picsum.photos/200/300"
          }
        })

        console.log({ result });
        setRequest([...request, ...result])

      }
    })()
  }, [])

  return (
    <div>
      <Head>
        <title>Lofi-App by Achraf Garai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GenerateMusic />
      <Grid>
        <div className="col-span-2">
          <h1 className="text-2xl font-medium">Playlists</h1>
          <div className="flex flex-col gap-16">
            {request.map((playlist: any) => (
              <PlaylistCard
                key={playlist.id}
                id={playlist.id}
                title={playlist.title}
                img={playlist.imageUrl}
              />
            ))}
          </div>
        </div>
        <div className="flex flex-col gap-8">
          <h1 className="text-xl font-medium">Top Artists</h1>
          <div className="flex flex-col gap-4">
            {data.Artists.map((artist: any) => (
              <ArtistCard
                key={artist.id}
                name={artist.name}
                id={artist.id}
                imgUrl={artist.imageUrl}
              />
            ))}
          </div>
          <About />
        </div>
      </Grid>
    </div>
  )
}

export default Home
function cn(root: any): string | undefined {
  throw new Error('Function not implemented.')
}
